### ISSUE TITLE
Result does not match

### ISSUE THREAD

**Issue by GaryLu2023** [CCSI-Toolset/MEA_ssm#23]
I have tried the model as described in the document, but I find that the fraction of substances in the stream ABSLEAN is not matching the one provided in the document. It shows a fraction of 7.91146 H2O, 0.1 CO2, and 1 MEA, which does not really make sense since they do not add up to 1. If I change the fraction as provided, then there will be an error occur in the sensitivity block on case 5 with 4500 flowrates. If I do not change the fraction, the result came perfectly as described in the document. 
<img width="402" alt="New Model Result with change" src="https://github.com/CCSI-Toolset/MEA_ssm/assets/152109830/f09e3ba6-cc47-4d5f-a36f-ab3070d98784">
<img width="206" alt="OG fraction" src="https://github.com/CCSI-Toolset/MEA_ssm/assets/152109830/939e74c6-5d67-4821-9cbd-3295191048d3">

**Comment by bpaul4** [comment]
As @jmorgan29 mentioned in his reply, the values are scaled intentionally so that the CO2 specification corresponds to the lean loading (everything scales using MEA as the basis of 1). I did use Aspen V12 to test the original model, then changing ABSLEAN to more exact rounding dividing by the total of 9.01146 and finally with your values. I confirmed that the first two cases solve successfully yielding the same results while the last case encounters a FORTRAN error. The last case actually gives a loading of 0.1446, not 0.1, which is why the model gives different results when that condition is enforced.
